- Create package name as week1.day1
- Create a  new class as "Iphone" under week1.day1
- Create 2 methods (makeCall() , model()) with simple print statement
- Create main method in another Class as SmartPhone
- Create object for Iphone class and call the methods using the object
- Execute the class and get the result in console
